export const GROUPS = {
  ATTRIBUTE_MAPPER_GROUP: 'ATTRIBUTE-MAPPER-GROUP',
};

export const TOPICS = {
  ENTITY_MAPPER_TOPIC: 'ENTITY-MAPPER-TOPIC',
};

export const ENTITY_MAPPER_EVENT_TYPE = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
};
